# Generated by Django 5.1.3 on 2024-11-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_package_place_place_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_price',
            new_name='place_attraction',
        ),
    ]
