# Generated by Django 5.1.3 on 2024-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_rename_place_price_place_place_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_attraction',
            field=models.TextField(default='Attraction'),
        ),
    ]
