# Generated by Django 5.1.3 on 2024-11-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
