# Generated by Django 5.1.3 on 2024-11-29 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0008_package_price_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('number_of_people', models.PositiveIntegerField()),
                ('arrival_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('phone_number', models.BigIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
